name: tests
on: push
jobs:
  tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup cmake
          uses: jwlawson/actions-setup-cmake@v1.7
          with:
            cmake-version: '3.16.x'

        - name: Install google test
          run: git clone https://github.com/google/googletest.git &&
               cd googletest &&
               sudo mkdir /usr/include/google_test &&
               sudo cp -r googletest/include /usr/include/google_test &&
               mkdir build &&
               cd build && 
               cmake .. &&
               make &&
               sudo cp lib/* /usr/local/lib

        - name: Run tests
          run: make test

